-- Add image_url column to certifications table
ALTER TABLE public.certifications ADD COLUMN IF NOT EXISTS image_url text;

-- Add image_url column to achievements table
ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS image_url text;

-- Insert sample certifications
INSERT INTO public.certifications (title, issuer, issue_date, credential_id, credential_url, display_order, image_url) VALUES
('Certified Ethical Hacker (CEH)', 'EC-Council', '2024-03-15', 'CEH-12345678', 'https://www.eccouncil.org/verify', 1, NULL),
('OSCP - Offensive Security Certified Professional', 'Offensive Security', '2023-11-20', 'OS-98765432', 'https://www.offensive-security.com/verify', 2, NULL),
('AWS Certified Security - Specialty', 'Amazon Web Services', '2024-01-10', 'AWS-SEC-2024', 'https://aws.amazon.com/verification', 3, NULL),
('CompTIA Security+', 'CompTIA', '2023-06-25', 'COMP-SEC-456', 'https://www.comptia.org/verify', 4, NULL);

-- Insert sample achievements
INSERT INTO public.achievements (title, description, date, icon_name, display_order, image_url) VALUES
('1st Place - National CTF Championship', 'Won first place in the National Capture The Flag competition, solving 45 out of 50 challenges across web, crypto, and binary exploitation categories.', '2024-06-15', 'Trophy', 1, NULL),
('Bug Bounty Hall of Fame - Google', 'Recognized in Google''s Security Hall of Fame for discovering a critical authentication bypass vulnerability affecting Google Cloud Platform.', '2024-02-20', 'Award', 2, NULL),
('Published Security Research Paper', 'Authored a peer-reviewed paper on "Advanced Techniques in API Security Testing" published in the Journal of Cybersecurity Research.', '2023-09-10', 'BookOpen', 3, NULL),
('DEF CON Speaker', 'Presented research on "Breaking Modern Authentication Systems" at DEF CON 32, one of the world''s largest hacking conferences.', '2024-08-08', 'Mic', 4, NULL);

-- Insert sample projects
INSERT INTO public.projects (title, description, technologies, github_url, demo_url, featured, display_order, image_url) VALUES
('VulnScanner Pro', 'An automated vulnerability scanner for web applications that identifies OWASP Top 10 vulnerabilities with detailed remediation guidance.', ARRAY['Python', 'Flask', 'Docker', 'PostgreSQL'], 'https://github.com/example/vulnscanner', 'https://vulnscanner-demo.example.com', true, 1, NULL),
('SecureAuth Framework', 'A comprehensive authentication framework implementing OAuth 2.0, SAML, and passwordless authentication with built-in security best practices.', ARRAY['TypeScript', 'Node.js', 'Redis', 'JWT'], 'https://github.com/example/secureauth', NULL, true, 2, NULL),
('NetworkGuard', 'Real-time network traffic analyzer and intrusion detection system with machine learning-based anomaly detection.', ARRAY['Go', 'TensorFlow', 'Elasticsearch', 'Grafana'], 'https://github.com/example/networkguard', 'https://networkguard.example.com', false, 3, NULL),
('CryptoAudit Tool', 'Automated cryptographic implementation auditor that detects weak algorithms, improper key management, and encryption vulnerabilities.', ARRAY['Rust', 'WebAssembly', 'React'], 'https://github.com/example/cryptoaudit', NULL, false, 4, NULL);

-- Insert sample blog posts
INSERT INTO public.blog_posts (title, slug, excerpt, content, author, tags, published, image_url) VALUES
('Understanding Zero-Day Vulnerabilities: A Deep Dive', 'understanding-zero-day-vulnerabilities', 'Explore the world of zero-day vulnerabilities, how they''re discovered, and the ethical considerations surrounding their disclosure.', E'# Understanding Zero-Day Vulnerabilities\n\nZero-day vulnerabilities represent one of the most critical threats in cybersecurity today. These are security flaws that are unknown to the software vendor and, therefore, have no available patches or fixes.\n\n## What Makes Zero-Days Dangerous?\n\nThe term "zero-day" refers to the fact that developers have had zero days to fix the vulnerability before it becomes known or exploited. This window of exposure can last anywhere from hours to months, depending on when the vulnerability is discovered and how quickly a patch can be developed.\n\n## Discovery Methods\n\n- **Fuzzing**: Automated testing with random inputs\n- **Code Review**: Manual analysis of source code\n- **Reverse Engineering**: Analyzing compiled binaries\n- **Bug Bounty Programs**: Crowdsourced security testing\n\n## Responsible Disclosure\n\nWhen security researchers discover zero-day vulnerabilities, they face an ethical dilemma: disclose immediately (risking exploitation) or wait for a patch (potentially leaving users vulnerable longer).\n\n## Protection Strategies\n\n1. Keep systems updated\n2. Implement defense in depth\n3. Monitor for anomalous behavior\n4. Use application whitelisting', 'Sibin Raj', ARRAY['Security', 'Zero-Day', 'Vulnerabilities'], true, NULL),
('API Security Best Practices for 2024', 'api-security-best-practices-2024', 'A comprehensive guide to securing your APIs against modern attack vectors, including authentication, rate limiting, and input validation.', E'# API Security Best Practices for 2024\n\nAPIs have become the backbone of modern applications, but they also represent a significant attack surface. Here''s how to secure them effectively.\n\n## Authentication & Authorization\n\n### OAuth 2.0 Implementation\n```javascript\n// Always use authorization code flow for web apps\nconst config = {\n  grantType: ''authorization_code'',\n  pkce: true,\n  tokenExpiry: ''15m''\n};\n```\n\n## Rate Limiting\n\nImplement progressive rate limiting:\n- 100 requests/minute for authenticated users\n- 10 requests/minute for unauthenticated\n- Exponential backoff on repeated violations\n\n## Input Validation\n\nNever trust client input. Validate everything:\n- Data types\n- Length constraints\n- Format patterns\n- Business logic rules\n\n## Security Headers\n\nEssential headers for API responses:\n- `X-Content-Type-Options: nosniff`\n- `X-Frame-Options: DENY`\n- `Content-Security-Policy`\n\n## Monitoring & Logging\n\nLog all API activity for forensic analysis while ensuring PII is properly redacted.', 'Sibin Raj', ARRAY['API', 'Security', 'Best Practices'], true, NULL),
('The Rise of AI in Penetration Testing', 'ai-in-penetration-testing', 'How artificial intelligence is revolutionizing the field of penetration testing, from automated reconnaissance to intelligent vulnerability analysis.', E'# The Rise of AI in Penetration Testing\n\nArtificial intelligence is transforming how security professionals approach penetration testing, making it more efficient and comprehensive than ever before.\n\n## AI-Powered Reconnaissance\n\nModern AI tools can:\n- Map attack surfaces automatically\n- Identify technology stacks from minimal data\n- Correlate information from multiple sources\n- Predict potential vulnerability patterns\n\n## Intelligent Fuzzing\n\nAI-driven fuzzers learn from previous inputs to generate more effective test cases, significantly reducing the time needed to discover vulnerabilities.\n\n## Automated Exploitation\n\nWhile ethical concerns exist, AI can:\n- Chain multiple vulnerabilities\n- Adapt payloads in real-time\n- Navigate complex authentication flows\n\n## The Human Element\n\nDespite AI advances, human expertise remains crucial for:\n- Creative thinking and novel attack vectors\n- Business logic vulnerabilities\n- Social engineering assessments\n- Final verification and reporting\n\n## Future Outlook\n\nAs AI continues to evolve, we''ll see more sophisticated tools that augment human capabilities rather than replace them entirely.', 'Sibin Raj', ARRAY['AI', 'Penetration Testing', 'Automation'], true, NULL);